apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcd-example-deployment
  labels:
    app: pcd-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcd-example
  template:
    metadata:
      labels:
        app: pcd-example
    spec:
      containers:
        - name: pcd-example-container
          image: msnishan/pcd-example:0.0.2
          envFrom:
            - configMapRef:
                name: pcd-configmap
            - secretRef:
                name: pcd-secret
