spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always

gcp:
  project:
    id: ${GCP_PROJECT_ID}
    sub: ${GCP_SUB_ID}
logging:
  level:
    root: INFO
    com.google.cloud.pubsub: DEBUG